/* Modo online gratuito: Firebase RTDB sincroniza una única fase para todos. */
(function () {
  'use strict';
  const K='impostorFutbolero_free_v1', MAX=12, D={facil:'Cracks súper conocidos por todos, ideal para grupos casuales.',medio:'Jugadores conocidos por hinchas del fútbol, un poco más de desafío.',dificil:'Cracks difíciles de adivinar. Para compensar, se da más información sobre ellos.'};
  const $=id=>document.getElementById(id), esc=v=>{const e=document.createElement('div');e.textContent=v||'';return e.innerHTML;}, stage=id=>document.querySelectorAll('.stage').forEach(e=>e.classList.toggle('active',e.id===id));
  let db,uid,code,room,ref,rr,offset=0,hb,tick,opening=false,role=null,roleRound=null,shown=false,busy=false;
  const now=()=>Date.now()+offset, path=()=>`rooms/${code}`, ps=()=>room?.players||{}, ids=()=>Object.keys(ps()), me=()=>ps()[uid], phase=()=>room?.phase||'lobby', privatePath=(round,id)=>`privateRounds/${code}/${round}/${id}`;
  const stale=()=>{const h=ps()[room?.hostId];return !!h&&now()-Number(h.lastSeenAt||0)>45000}, host=()=>!!room&&(room.hostId===uid||(room.backupHostId===uid&&stale()));
  const active=()=>ids().filter(id=>room.roundRoster?.[id]&&!ps()[id].eliminated&&!ps()[id].excluded), sorted=()=>ids().sort((a,b)=>Number(ps()[a].joinedAt||0)-Number(ps()[b].joinedAt||0));
  const save=()=>localStorage.setItem(K,JSON.stringify({code})), clear=()=>localStorage.removeItem(K), load=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch(_){return null}};
  const err=e=>e?.code==='PERMISSION_DENIED'?'No se pudo hacer esa acción. Revisa tu conexión o vuelve a entrar a la sala.':e?.message||'No se pudo completar la acción.';
  async function run(fn,btn){try{if(btn){btn.dataset.t=btn.textContent;btn.disabled=true;btn.textContent='Procesando…'}return await fn()}catch(e){console.error(e);alert(err(e));throw e}finally{if(btn){btn.disabled=false;btn.textContent=btn.dataset.t||btn.textContent}}}
  const shuffle=a=>{a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  const record=(name,isHost)=>({name,isHost,joinedAt:now(),lastSeenAt:now(),eliminated:false,excluded:false});
  const roomCode=()=>{const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join('')};
  const nameOf=s=>{s=String(s||'').trim().replace(/\s+/g,' ');if(!s||s.length>16)throw Error('Escribe un nombre de 1 a 16 caracteres.');return s};

  async function boot(){
    try{
      if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);
      if(firebaseConfig.appCheckSiteKey&&firebase.appCheck)firebase.appCheck().activate(firebaseConfig.appCheckSiteKey,true);
      await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL);if(!firebase.auth().currentUser)await firebase.auth().signInAnonymously();
      uid=firebase.auth().currentUser.uid;db=firebase.database();db.ref('.info/serverTimeOffset').on('value',s=>offset=Number(s.val())||0);bind();
      const old=load();if(old?.code){code=old.code;attach()}else invite();
    }catch(e){console.error(e);alert('No se pudo iniciar el modo online. Activa Authentication > Anónimo en Firebase.')}
  }
  function attach(){
    detach();if(!code)return;ref=db.ref(path());ref.on('value',s=>{const v=s.val();if(!v){alert('La sala se cerró.');leaveLocal();return}if(!v.players?.[uid]){alert('Ya no formas parte de esta sala.');leaveLocal();return}room=v;render()},e=>console.error(e));
    rr=db.ref(`reactions/${code}`).limitToLast(12);const at=now();rr.on('child_added',s=>{const x=s.val();if(x&&Number(x.at||0)>=at-1200)reaction(x.emoji,x.name)});heartbeat();hb=setInterval(heartbeat,15000);
  }
  function detach(){if(ref)ref.off();if(rr)rr.off();if(hb)clearInterval(hb);if(tick)clearInterval(tick);ref=rr=hb=tick=null;opening=false}
  function leaveLocal(){detach();code=room=role=null;roleRound=null;clear();stage('stage-mode')}
  function heartbeat(){if(code&&document.visibilityState==='visible')db.ref(`${path()}/players/${uid}/lastSeenAt`).set(now()).catch(console.warn)}
  async function create(name){for(let i=0;i<15;i++){const c=roomCode(), data={hostId:uid,backupHostId:null,phase:'lobby',round:0,difficulty:'facil',impostors:1,timerSeconds:60,score:{team:0,impostors:0},createdAt:now(),players:{[uid]:record(name,true)}};const r=await db.ref(`rooms/${c}`).transaction(x=>x===null?data:undefined,undefined,false);if(r.committed)return c}throw Error('No se pudo crear un código libre. Intenta otra vez.')}
  async function join(c,name){c=String(c||'').trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{6}$/.test(c))throw Error('El código de sala no es válido.');const r=await db.ref(`rooms/${c}/players/${uid}`).transaction(x=>x||record(name,false),undefined,false);if(!r.committed&&!r.snapshot.exists())throw Error('No se pudo entrar a esa sala. Revisa el código.');try{await db.ref(`rooms/${c}/backupHostId`).transaction(x=>x||uid,undefined,false)}catch(_){}return c}

  function render(){if(roleRound!==room.round){roleRound=room.round;role=null;shown=false}if(phase()==='lobby'){lobby();stage('stage-room-lobby')}else if(phase()==='roles')roles();else if(['debate','voting','result'].includes(phase())){debate();stage('stage-room-wait')}else if(phase()==='reveal'){reveal();stage('stage-room-reveal')}}
  function lobby(){const a=sorted(),h=host(),imp=Number(room.impostors||1);$('lobbyCode').textContent=code;$('lobbyPlayerCount').textContent=a.length;$('lobbyPlayerList').innerHTML=a.map(id=>`<div class="player-row"><span>${esc(ps()[id].name)}${id===uid?' (tú)':''}</span><span class="tag">${id===room.hostId?'ANFITRIÓN':id===room.backupHostId?'RESPALDO':''}</span></div>`).join('');$('lobbyHostControls').style.display=h?'block':'none';$('lobbyWaitingMsg').style.display=h?'none':'block';$('impostorCountRoom').textContent=imp;$('minusImpostorsRoom').disabled=!h||imp<=1;$('plusImpostorsRoom').disabled=!h||imp>=Math.max(1,a.length-2);document.querySelectorAll('#diffPillsRoom .pill').forEach(x=>x.classList.toggle('active',x.dataset.diff===room.difficulty));$('diffDescRoom').textContent=D[room.difficulty]||D.facil;$('startRoomBtn').disabled=!h||a.length<3;$('startRoomHint').style.display=a.length<3?'block':'none';$('leaveRoomBtn').textContent=room.hostId===uid?'Cerrar sala':'Salir de la sala'}
  async function roles(){const o=room.turnOrder||[],i=Number(room.turnIndex||0),turn=o[i];if(turn===uid){if(!role)try{role=(await db.ref(privatePath(room.round,uid)).once('value')).val()}catch(e){console.warn(e)}if(!role)return;myRole();stage('stage-room-play')}else{const mine=o.indexOf(uid);$('turnPlayerName').textContent=ps()[turn]?.name||'—';$('turnEyebrowState').textContent=mine<i?'Ya viste tu carta':'Falta poco para tu turno';$('turnSubtitle').textContent=mine<i?'Espera a que terminen los demás. No comentes nada de tu rol todavía.':'Mira el celular cuando te toque y gira tu carta sin que nadie más vea.';$('turnPlayerList').innerHTML=o.map((id,n)=>`<div class="player-row${n===i?' current-turn':''}"><span>${esc(ps()[id]?.name||'Jugador')}${id===uid?' (tú)':''}</span><span class="tag">${n<i?'✓ Ya vio su rol':n===i?'🔔 Su turno':'Espera'}</span></div>`).join('');stage('stage-room-turnwait')}}
  function myRole(){const imp=role.role==='impostor';$('cardRoom').classList.toggle('flipped',shown);$('cardBackRoom').classList.toggle('role-impostor',imp);$('roleTagRoom').textContent=imp?'ATENCIÓN':'TU CRACK ES';$('roleNameRoom').textContent=imp?'SOS EL IMPOSTOR':role.name;$('roleNickRoom').textContent=imp?'':role.nickname;$('roleDescRoom').textContent=imp?'No sabes quién es el crack. Escucha a los demás e improvisa sin que te descubran.':role.description;$('actionBtnRoom').textContent=shown?'Listo, pasar turno':'Ver mi rol'}
  function debate(){const p=phase(),a=active(),key=room.voteKey||'',v=room.votes?.[key]||{};$('debateRoundLabel').textContent='Ronda '+(room.round||1);$('waitTitle').innerHTML=p==='voting'?'A <span>VOTAR</span>':p==='result'?'RESULTADO<br><span>DE LA RONDA</span>':'A <span>DEBATIR</span>';$('waitSubtitle').textContent=p==='voting'?'Toca “Votar” junto al nombre de quien creas que es el impostor.':p==='result'?'':'Cada jugador dice una palabra o frase sobre el crack, sin decirlo directo.';$('emojiRow').style.display=p==='debate'&&!me()?.eliminated?'flex':'none';timer(p);$('waitPlayerCount').textContent=a.length;$('waitPlayerList').innerHTML=sorted().map(id=>{const q=ps()[id],off=q.eliminated||q.excluded||!room.roundRoster?.[id];let t='',b='';if(off)t=q.excluded?'⏸ No participa esta ronda':q.eliminated?'❌ Eliminado':'👀 Espectador';else if(p==='voting'){if(id===uid)t=v[uid]?'✓ Ya votaste':'';else if(v[id])t='✓ Votó';if(!v[uid]&&id!==uid)b=`<button class="vote-btn" data-vote="${id}" type="button">Votar</button>`}return `<div class="player-row${off?' eliminated':''}"><span>${esc(q.name)}${id===uid?' (tú)':''}</span><span class="tag">${t}</span>${b}</div>`}).join('');document.querySelectorAll('[data-vote]').forEach(b=>b.addEventListener('click',()=>vote(b.dataset.vote,b)));voteControls(p,a,v);const r=room.lastEliminated;$('roundResultBox').style.display=p==='result'&&r?'block':'none';if(p==='result'&&r){$('roundResultText').textContent=`❌ ${r.name} fue eliminado — era ${r.wasImpostor?'el impostor':'del equipo'}${r.wasTiebreak?' (segundo empate: sorteo entre empatados)':''}`;$('nextRoundBtn').style.display=host()?'block':'none';$('nextRoundWaitMsg').style.display=host()?'none':'block'}$('cancelGameBtn').style.display=host()&&p!=='result'?'block':'none'}
  function voteControls(p,a,v){const b=$('resolveVoteBtn'),m=$('voteWaitMsg');if(p!=='voting'){b.style.display=m.style.display='none';return}const n=a.filter(id=>v[id]).length,all=a.length>0&&n===a.length;if(host()){b.style.display='block';b.disabled=false;b.dataset.mode=all?'resolve':'omit';b.textContent=all?'Ver resultado de la votación':`Esperando votos (${n}/${a.length}) · Omitir ausente`;m.style.display='none'}else{b.style.display='none';m.style.display='block';m.textContent=`Votos: ${n}/${a.length}`}}
  function timer(p){if(tick){clearInterval(tick);tick=null}const d=$('timerDisplay'),c=$('timerHostControls');$('timerSecondsLabel').textContent=(room.timerSeconds||60)+'s';if(p==='voting'){c.style.display='none';d.textContent='🗳️ ¡A votar!';return}if(p==='result'){c.style.display='none';d.textContent='--:--';return}c.style.display=host()?'block':'none';if(!room.timerEndsAt){d.textContent='--:--';$('startTimerBtn').textContent='Iniciar cronómetro';return}$('startTimerBtn').textContent='Detener cronómetro';const f=()=>{const n=Math.max(0,Math.ceil((Number(room.timerEndsAt)-now())/1000));d.textContent=String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');if(n===0&&!opening){opening=true;db.ref().update({[`${path()}/phase`]:'voting',[`${path()}/timerEndsAt`]:null,[`${path()}/votingStartedAt`]:now(),[`${path()}/voteKey`]:`${room.round}_0`}).catch(console.warn).finally(()=>opening=false)}};f();tick=setInterval(f,500)}
  function reveal(){const s=room.score||{},r=room.revealRoles||{};$('scoreTeam').textContent=s.team||0;$('scoreImpostors').textContent=s.impostors||0;$('winnerBanner').textContent=room.lastWinner==='team'?'✅ Ganó el equipo esta partida':'❌ Ganaron los impostores esta partida';$('secretNameRoom').textContent=room.revealedSecretName||'—';$('revealListRoom').innerHTML=sorted().map(id=>`<div class="reveal-row${r[id]==='impostor'?' impostor':''}"><span>${esc(ps()[id].name)}${id===uid?' (tú)':''}</span><span>${r[id]==='impostor'?'IMPOSTOR':'Equipo'}</span></div>`).join('');$('revealHostControls').style.display=host()?'block':'none';$('revealWaitMsg').style.display=host()?'none':'block';const h=Object.values(room.history||{}).sort((a,b)=>Number(b.at||0)-Number(a.at||0)).slice(0,10);$('historyList').innerHTML=h.length?h.map(x=>`<div class="history-row"><span>${esc(x.secretName)}</span><span class="tag">${x.winner==='team'?'✅ Equipo':'❌ Impostores'}</span></div>`).join(''):'<p class="waiting-msg">Todavía no hay rondas anteriores.</p>';$('leaveRoomBtn2').textContent=room.hostId===uid?'Cerrar sala':'Salir de la sala'}
  function reaction(emoji,name){const l=$('reactionLayer');if(!l)return;const e=document.createElement('div');e.className='floating-reaction';e.style.left=(10+Math.random()*70)+'%';e.innerHTML=`<span class="fr-emoji">${esc(emoji)}</span><span class="fr-who">${esc(name)}</span>`;l.appendChild(e);setTimeout(()=>e.remove(),1800)}

  async function config(x){if(!host()||phase()!=='lobby')throw Error('Solo el anfitrión puede cambiar la configuración.');const u={};Object.entries(x).forEach(([k,v])=>u[`${path()}/${k}`]=v);await db.ref().update(u)}
  async function start(){if(!host())throw Error('Solo el anfitrión puede iniciar.');if(!['lobby','reveal'].includes(phase()))throw Error('La ronda actual todavía no terminó.');const a=ids();if(a.length<3)throw Error('Se necesitan al menos 3 jugadores.');const diff=PLAYERS_DB[room.difficulty]?room.difficulty:'facil',rnd=Number(room.round||0)+1,secret=PLAYERS_DB[diff][Math.floor(Math.random()*PLAYERS_DB[diff].length)],imps=new Set(shuffle(a).slice(0,Math.min(Math.max(1,Number(room.impostors||1)),a.length-2))),order=shuffle(a),u={[`${path()}/phase`]:'preparing',[`${path()}/round`]:rnd,[`${path()}/turnOrder`]:order,[`${path()}/turnIndex`]:0,[`${path()}/roundRoster`]:Object.fromEntries(a.map(id=>[id,true])),[`${path()}/timerEndsAt`]:null,[`${path()}/voteKey`]:'',[`${path()}/votingStartedAt`]:null,[`${path()}/lastEliminated`]:null,[`${path()}/lastWinner`]:null,[`${path()}/revealedSecretName`]:null,[`${path()}/revealRoles`]:null};a.forEach(id=>{u[`${path()}/players/${id}/eliminated`]=false;u[`${path()}/players/${id}/excluded`]=false});await db.ref().update(u);const roles={},z={};a.forEach(id=>{const r=imps.has(id)?'impostor':'crack';roles[id]=r;z[privatePath(rnd,id)]=r==='impostor'?{role:r,round:rnd}:{role:r,round:rnd,name:secret[0],nickname:secret[1],description:secret[2]}});z[`privateRounds/${code}/${rnd}/hostState`]={roles,secretName:secret[0]};await db.ref().update(z);await db.ref(`${path()}/phase`).set('roles')}
  async function nextTurn(){const o=room.turnOrder||[],i=Number(room.turnIndex||0);if(phase()!=='roles'||o[i]!==uid)throw Error('No es tu turno.');const n=i+1,u={[`${path()}/turnIndex`]:n};if(n>=o.length)u[`${path()}/phase`]='debate';await db.ref().update(u)}
  async function vote(target,b){if(busy)return;busy=true;try{if(phase()!=='voting'||!room.voteKey||target===uid||!active().includes(target))throw Error('Ese voto no es válido.');await run(()=>db.ref(`${path()}/votes/${room.voteKey}/${uid}`).set(target),b)}finally{busy=false}}
  async function omit(){if(!host())throw Error('Solo el anfitrión puede omitir a un ausente.');if(now()-Number(room.votingStartedAt||now())<30000)throw Error('Espera 30 segundos antes de omitir a un ausente.');const v=room.votes?.[room.voteKey]||{},missing=active().filter(id=>id!==uid&&!v[id]&&now()-Number(ps()[id].lastSeenAt||0)>25000);if(!missing.length)throw Error('Aún no hay un jugador ausente que se pueda omitir.');const u={};missing.forEach(id=>u[`${path()}/players/${id}/excluded`]=true);await db.ref().update(u)}
  async function resolve(){if(!host())throw Error('Solo el anfitrión puede resolver.');const a=active(),v=room.votes?.[room.voteKey]||{};if(a.some(id=>!v[id]))throw Error('Aún faltan votos. Puedes esperar u omitir a un ausente.');const t={};a.forEach(id=>{if(a.includes(v[id]))t[v[id]]=(t[v[id]]||0)+1});const max=Math.max(0,...Object.values(t));let top=Object.keys(t).filter(id=>t[id]===max);if(!top.length)top=a.slice();const attempt=Number((room.voteKey||'').split('_')[1]||0);if(top.length>1&&attempt===0){await db.ref().update({[`${path()}/voteKey`]:`${room.round}_1`,[`${path()}/votingStartedAt`]:now()});return}const out=top.length===1?top[0]:top[Math.floor(Math.random()*top.length)],state=(await db.ref(`privateRounds/${code}/${room.round}/hostState`).once('value')).val();if(!state?.roles)throw Error('No se pudo leer el resultado. Inicia una nueva ronda.');const roles=state.roles,left=a.filter(id=>id!==out),imps=left.filter(id=>roles[id]==='impostor'),team=left.filter(id=>roles[id]!=='impostor'),u={[`${path()}/players/${out}/eliminated`]:true,[`${path()}/lastEliminated`]:{id:out,name:ps()[out].name,wasImpostor:roles[out]==='impostor',wasTiebreak:top.length>1}};if(!imps.length||imps.length>=team.length){const winner=!imps.length?'team':'impostors',at=now(),hist=Object.assign({},room.history||{});hist[at]={secretName:state.secretName,winner,at};const q=Object.entries(hist).sort((a,b)=>Number(a[1].at)-Number(b[1].at));while(q.length>30)delete hist[q.shift()[0]];Object.assign(u,{[`${path()}/phase`]:'reveal',[`${path()}/lastWinner`]:winner,[`${path()}/score/${winner}`]:Number(room.score?.[winner]||0)+1,[`${path()}/revealedSecretName`]:state.secretName,[`${path()}/revealRoles`]:roles,[`${path()}/history`]:hist})}else u[`${path()}/phase`]='result';await db.ref().update(u)}
  const lobbyBack=()=>{if(!host())throw Error('Solo el anfitrión puede cambiar la partida.');return db.ref().update({[`${path()}/phase`]:'lobby',[`${path()}/timerEndsAt`]:null,[`${path()}/lastEliminated`]:null,[`${path()}/voteKey`]:''})};
  async function leave(){if(room.hostId===uid)await db.ref(path()).remove();else await db.ref(`${path()}/players/${uid}`).remove();leaveLocal()}
  function bind(){
    $('modeOnlineBtn').onclick=()=>stage('stage-room-menu');$('backToModeBtn2').onclick=()=>stage('stage-mode');$('joinCodeInput').oninput=function(){this.value=this.value.toUpperCase().replace(/[^A-Z2-9]/g,'')};
    $('createRoomBtn').onclick=async()=>{try{const n=nameOf($('roomNameInput').value);$('roomError').textContent='';code=await run(()=>create(n),$('createRoomBtn'));save();attach()}catch(e){$('roomError').textContent=err(e)}};
    $('joinRoomBtn').onclick=async()=>{try{const n=nameOf($('roomNameInput').value);$('roomError').textContent='';code=await run(()=>join($('joinCodeInput').value,n),$('joinRoomBtn'));save();attach()}catch(e){$('roomError').textContent=err(e)}};
    $('minusImpostorsRoom').onclick=()=>run(()=>config({impostors:Math.max(1,Number(room.impostors||1)-1)}));$('plusImpostorsRoom').onclick=()=>run(()=>config({impostors:Math.min(ids().length-2,Number(room.impostors||1)+1)}));document.querySelectorAll('#diffPillsRoom .pill').forEach(e=>e.onclick=()=>run(()=>config({difficulty:e.dataset.diff})));$('startRoomBtn').onclick=()=>run(start,$('startRoomBtn'));
    $('actionBtnRoom').onclick=async()=>{if(!shown){shown=true;myRole();return}await run(nextTurn,$('actionBtnRoom'))};$('minusTimerBtn').onclick=()=>run(()=>config({timerSeconds:Math.max(15,Number(room.timerSeconds||60)-15)}));$('plusTimerBtn').onclick=()=>run(()=>config({timerSeconds:Math.min(300,Number(room.timerSeconds||60)+15)}));$('startTimerBtn').onclick=()=>run(()=>{if(!host())throw Error('Solo el anfitrión controla el cronómetro.');return db.ref(`${path()}/timerEndsAt`).set(room.timerEndsAt?null:now()+Number(room.timerSeconds||60)*1000)},$('startTimerBtn'));
    $('resolveVoteBtn').onclick=()=>run(()=>$('resolveVoteBtn').dataset.mode==='resolve'?resolve():omit(),$('resolveVoteBtn'));$('nextRoundBtn').onclick=()=>run(()=>{if(!host())throw Error('Solo el anfitrión puede continuar.');return db.ref().update({[`${path()}/phase`]:'debate',[`${path()}/lastEliminated`]:null,[`${path()}/timerEndsAt`]:null})},$('nextRoundBtn'));$('playAgainRoomBtn').onclick=()=>run(start,$('playAgainRoomBtn'));$('newConfigRoomBtn').onclick=()=>run(lobbyBack,$('newConfigRoomBtn'));$('cancelGameBtn').onclick=()=>{if(confirm('¿Cancelar esta partida y volver a la sala de espera?'))run(lobbyBack,$('cancelGameBtn'))};
    ['leaveRoomBtn','leaveRoomBtn2'].forEach(id=>$(id).onclick=()=>{if(confirm(room?.hostId===uid?'¿Cerrar la sala para todos?':'¿Salir de la sala?'))run(leave)});$('emojiRow').onclick=e=>{const b=e.target.closest('[data-emoji]');if(b&&me())db.ref(`reactions/${code}`).push({emoji:b.dataset.emoji,name:me().name,at:now(),by:uid}).catch(console.warn)};$('shareCodeBtn').onclick=async()=>{const t=`Únete a mi sala de El Impostor Futbolero: ${location.origin}${location.pathname}?room=${code}`;try{if(navigator.share)await navigator.share({text:t});else await navigator.clipboard.writeText(t)}catch(_){}};$('whatsappInviteBtn').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent(`⚽ ¡Únete a mi sala de El Impostor Futbolero!\n${location.origin}${location.pathname}?room=${code}`),'_blank');document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')heartbeat()});
  }
  function invite(){const c=new URLSearchParams(location.search).get('room');if(c){$('joinCodeInput').value=c.toUpperCase();history.replaceState({},'',location.pathname);stage('stage-room-menu')}}
  boot();
})();
