// Base de datos de futbolistas para "El Impostor Futbolero"
// Cada entrada: [nombre, apodo, dato/descripción]
// En dificultad "dificil" las descripciones son más largas a propósito,
// para compensar que son cracks menos conocidos.

const PLAYERS_DB = {

  facil: [
    ["Lionel Messi","La Pulga","Ganó el Mundial con Argentina en 2022 y tiene 8 Balones de Oro."],
    ["Cristiano Ronaldo","CR7","Máximo goleador histórico del fútbol masculino según la FIFA."],
    ["Diego Maradona","El Pelusa","Hizo el gol 'Barrilete Cósmico' en México 86."],
    ["Pelé","O Rei","Único jugador en ganar tres Copas del Mundo."],
    ["Zinedine Zidane","Zizou","Cabezazo a Materazzi en la final del Mundial 2006."],
    ["Ronaldinho","El Mago","Jugaba con una sonrisa que desarmaba defensas enteras."],
    ["Ronaldo Nazário","El Fenómeno","Cambió el fútbol con su velocidad y gambeta en los 90."],
    ["Neymar Jr","El Ninja","El fichaje más caro de la historia, al PSG en 2017."],
    ["Kylian Mbappé","El Bólido","Campeón del mundo con Francia siendo adolescente."],
    ["Andrés Iniesta","El Ilusionista","Marcó el gol del título en la final del Mundial 2010."],
    ["Xavi Hernández","El Cerebro","Dirigía el mediocampo del Barça como un director de orquesta."],
    ["Zlatan Ibrahimović","El Imperator","Famoso por sus frases tan grandes como sus goles."],
    ["David Beckham","El Lord","Convirtió el fútbol en un fenómeno pop global."],
    ["Johan Cruyff","El Flaco","Inventó un giro que lleva su nombre."],
    ["George Best","El Quinto Beatle","Estrella del Manchester United con vida de rockstar."],
    ["Garrincha","El Ángel de Piernas Torcidas","Jugó con las piernas curvas y nunca perdió un Mundial."],
    ["Franz Beckenbauer","El Káiser","Reinventó la posición de líbero en la defensa."],
    ["Roberto Baggio","La Coleta Divina","Erró el penal decisivo del Mundial 94 y se hizo leyenda igual."],
    ["Paolo Maldini","El Elegante","Jugó en el Milan hasta los 40 años sin perder clase."],
    ["Iker Casillas","San Iker","Atajó el mano a mano decisivo en la final del Mundial 2010."],
    ["Gianluigi Buffon","Superman","Jugó Mundiales con más de 40 años en el arco."],
    ["Luis Suárez","El Pistolero","Mordió a un rival en pleno Mundial y aun así es ídolo."],
    ["Sergio Ramos","El Comandante","Metió el gol del descuento que salvó la Décima del Real Madrid."],
    ["Thierry Henry","Titi","Máximo goleador histórico del Arsenal."],
    ["Didier Drogba","El Elefante","Pidió la paz en Costa de Marfil después de clasificar al Mundial."],
    ["Samuel Eto'o","El León","Cuatro veces campeón de la Champions League."],
    ["Erling Haaland","El Robot","Rompió el récord de goles en una temporada de Premier League."],
    ["Vinícius Júnior","Vini Jr","Baila cada gol que mete con el Real Madrid."],
    ["Karim Benzema","El Gato","Ganó el Balón de Oro después de años como socio de Cristiano."],
    ["Luka Modrić","El General","Ganó el Balón de Oro rompiendo la racha de Messi y Cristiano."],
    ["Mohamed Salah","El Rey de Egipto","Ídolo total en Liverpool y en todo Egipto."],
    ["Antoine Griezmann","El Principito","Campeón del mundo 2018 y una de las figuras del Atlético."],
    ["Kevin De Bruyne","El Belga","Uno de los mejores asistidores de la historia de la Premier League."],
    ["Robert Lewandowski","El Polaco","Metió 5 goles en 9 minutos en un partido de Bundesliga."],
    ["Harry Kane","El Capitán","Máximo goleador histórico de la selección inglesa."],
    ["Jude Bellingham","El Niño Prodigio","Se fue de Inglaterra a los 17 años para triunfar en Europa."],
    ["Sadio Mané","El Guerrero","Volvió a África campeón de la Copa Africana con Senegal."],
    ["Wayne Rooney","El Niño de Croxteth","Debutó como profesional a los 16 años en el Everton."],
    ["Steven Gerrard","El Capitán de Istambul","Remontó una final de Champions 3-0 en el entretiempo."],
    ["Alan Shearer","El Cañonero","Máximo goleador histórico de la Premier League."],
    ["Pedri","El Heredero","A los 18 años ya era titular indiscutido del Barça."],
    ["Gareth Bale","El Galés","Metió una chilena espectacular en una final de Champions League."],
    ["Raúl González","El Séptimo","Capitán histórico del Real Madrid y su goleador durante más de una década."],
    ["Fernando Torres","El Niño","Ídolo del Atlético de Madrid y campeón de Europa con España."],
    ["David Villa","El Guaje","Máximo goleador histórico de la selección española."],
    ["Ryan Giggs","El Galés Volador","Jugó más de 20 temporadas seguidas en el Manchester United."],
    ["Paul Scholes","El Silencioso","Uno de los mediocampistas más respetados por rivales de su generación."],
    ["Frank Lampard","Súper Frank","Máximo goleador histórico del Chelsea, siendo mediocampista."],
    ["John Terry","JT","Capitán histórico del Chelsea campeón de Champions League."],
    ["Petr Čech","El Casco","Jugaba con un casco protector tras una fractura de cráneo."],
    ["Edwin van der Sar","El Muro Holandés","Arquero histórico del Manchester United y del Ajax."],
    ["Dennis Bergkamp","El Hombre No Voladora","Nunca viajaba en avión pero fue ídolo total del Arsenal."],
    ["Patrick Vieira","El Capitán Invencible","Lideró al Arsenal en su temporada invicta en la Premier League."],
    ["Michael Owen","El Niño de Oro","Metió un golazo histórico corriendo toda la cancha en el Mundial 98."],
    ["Peter Crouch","El Robot","Delantero altísimo famoso por su baile de festejo llamado 'el robot'."],
    ["Jamie Vardy","El Cuento de Hadas","Salió campeón de la Premier League con el Leicester como milagro deportivo."],
    ["N'Golo Kanté","El Incansable","Ganó ligas con dos clubes distintos y el Mundial con Francia, siempre humilde."],
    ["Paul Pogba","El Pogboom","Volante francés famoso por sus peinados y su festejo con baile."],
    ["Raphaël Varane","El Muro Francés","Ganó Champions Leagues y el Mundial siendo aún muy joven."],
    ["Hugo Lloris","El Capitán de los Bleus","Levantó la Copa del Mundo 2018 como arquero y capitán de Francia."],
    ["Olivier Giroud","El Elegante","Goleador francés recordado por sus goles de chilena y taco."],
    ["Marcus Rashford","El Chico de Manchester","Delantero surgido de la cantera del Manchester United."],
    ["Bukayo Saka","El Chico del Arsenal","Extremo inglés convertido en ídolo joven del Arsenal."],
    ["Phil Foden","El Pequeño Magο","Formado en la cantera del Manchester City, apodado así por Guardiola."],
    ["Jack Grealish","Las Medias Bajas","Famoso por jugar siempre con las medias caídas hasta el tobillo."],
    ["Trent Alexander-Arnold","El Lateral Asistidor","Lateral del Liverpool famoso por sus centros y tiros libres precisos."],
    ["Virgil van Dijk","El Gigante Holandés","Defensor central considerado de los mejores del mundo en su posición."],
    ["Alisson Becker","El Muro Brasileño","Arquero brasileño clave en los títulos del Liverpool."],
    ["Roberto Firmino","El Bobby","Delantero brasileño ídolo del Liverpool por su entrega y sonrisa."],
    ["Casemiro","El Escudo","Volante brasileño que ganó varias Champions League como recuperador."],
    ["Marcelo Vieira","El Rey de la Zurda","Lateral izquierdo brasileño, uno de los más ganadores del Real Madrid."],
    ["Toni Kroos","El Metrónomo Alemán","Uno de los mediocampistas con más títulos de Champions League."],
    ["Sergio Busquets","El Regalador de Espacios","Mediocampista clave del Barça y España durante más de una década."],
    ["Gerard Piqué","El Defensor Empresario","Ganó todo con el Barça y luego se volvió empresario del deporte."],
    ["Carles Puyol","El Capitán del Pelo Largo","Capitán histórico del Barça reconocible por su melena."],
    ["Thiago Silva","El Monstruo","Defensor central brasileño referente en PSG y Chelsea."],
    ["David Luiz","El de los Rulos","Defensor brasileño de pelo rizado famoso por sus goles de media distancia."],
    ["Alexis Sánchez","El Niño Maravilla","Estrella chilena campeona de dos Copas América seguidas."],
    ["Arturo Vidal","El Rey Arturo","Volante chileno de carácter fuerte, referente de la 'Generación Dorada'."],
    ["Edinson Cavani","El Matador","Delantero uruguayo goleador histórico del PSG."],
    ["Diego Godín","El Capitán del Cholo","Defensor central, símbolo del Atlético de Madrid de Simeone."],
    ["Diego Forlán","El Cachavacha","Máxima figura del Mundial 2010 pese a no ganarlo con Uruguay."],
    ["Rúben Dias","O Central","Defensor portugués pieza clave del Manchester City campeón de todo en una misma temporada."],
    ["Ángel Di María","El Fideo","Metió el gol del título en la final del Mundial 2022 con Argentina."],
    ["Sergio Agüero","El Kun","Metió el gol más dramático en el último minuto para salir campeón de la Premier League."],
    ["Javier Mascherano","El Jefecito","Capitán y líbero de la selección argentina durante más de una década."],
    ["Carlos Tévez","El Apache","Delantero argentino ídolo en Boca, River y clubes de Inglaterra."],
    ["Javier Zanetti","El Capitán Eterno","Jugó 19 temporadas en el Inter de Milán como capitán."],
    ["Mario Balotelli","Súper Mario","Delantero italiano tan talentoso como impredecible fuera de la cancha."],
    ["Marco Verratti","El Cerebrito","Volante italiano de toque exquisito, referente del PSG."],
    ["Gianluigi Donnarumma","Gigio","Se convirtió en arquero titular de la Juventus... de Italia siendo adolescente."],
    ["Alessandro Nesta","El Elegante Romano","Considerado uno de los defensores más finos de la historia italiana."],
    ["Giorgio Chiellini","El Guerrero","Defensor italiano campeón de la Eurocopa 2021 ya veterano."],
    ["Leonardo Bonucci","El Zurdo de Salida","Defensor central italiano famoso por sus pases largos precisos."],
    ["Thomas Müller","El Espacio Interpretador","Delantero alemán, se define a sí mismo como 'Raumdeuter', el intérprete del espacio."],
    ["Bastian Schweinsteiger","Basti","Campeón del mundo 2014 con Alemania, ícono del Bayern Múnich."],
    ["Mario Götze","El Héroe de Río","Metió el gol que le dio el título del Mundial 2014 a Alemania."],
    ["Marco Reus","El Capitán del Dortmund","Símbolo del Borussia Dortmund pese a nunca ganar la Champions."],
    ["Joshua Kimmich","El Todoterreno","Puede jugar de lateral o de volante central en la selección alemana."],
    ["İlkay Gündoğan","El Capitán del City","Volante alemán de origen turco, capitán del Manchester City campeón."],
    ["Michael Ballack","El Capitán sin Corona","Llegó segundo en Champions, Mundial y Eurocopa varias veces con Alemania."],
    ["Lukas Podolski","Poldi","Delantero alemán querido por su carisma dentro y fuera de la cancha."],
    ["Robert Pirès","El Elegante Francés","Extremo clave del Arsenal invicto en la Premier League."],
    ["Franck Ribéry","El Mago de Boulogne","Extremo francés estrella del Bayern Múnich con una marca en el rostro."],
    ["Marcel Desailly","El Roquero","Defensor francés campeón del mundo 1998 y de la Eurocopa 2000."],
    ["Laurent Blanc","El Presidente","Defensor central campeón del mundo 1998, luego dirigió a Francia."],
    ["Lilian Thuram","El Muro de Guadalupe","Metió dos goles clave en la semifinal del Mundial 1998, su único doblete en la selección."],
    ["Fabien Barthez","El Arquero Pelado","Arquero campeón del mundo 1998, famoso por su cabeza rapada."],
    ["Patrice Evra","El Lateral Bailarín","Lateral izquierdo campeón de Champions con el Manchester United."],
    ["Xabi Alonso","El Pasador Largo","Metió goles desde mitad de cancha y ganó todo con Liverpool y Real Madrid."],
    ["Teófilo Cubillas","El Nene","Delantero peruano estrella de los Mundiales de 1970 y 1978, ídolo máximo del fútbol de Perú."],
    ["Rodrygo Goes","El Niño Terrible","Delantero brasileño clave del Real Madrid en sus Champions League más recientes."],
    ["Endrick","El Chico Ferrari","Delantero brasileño que llegó al Real Madrid siendo una de las mayores promesas del mundo."],
    ["Lamine Yamal","El Chico de La Masia","Extremo español que debutó en el Barça siendo apenas un adolescente."],
    ["Gavi","El Niño Prodigio","Volante español, titular indiscutido del Barça desde muy joven."],
    ["Florian Wirtz","El Mago de Colonia","Volante alemán considerado una de las mayores joyas del fútbol europeo actual."],
    ["Federico Valverde","El Pentakill","Volante uruguayo todoterreno, pieza clave del Real Madrid moderno."],
    ["Julián Álvarez","La Araña","Delantero argentino campeón del mundo 2022, referente del Manchester City y luego del Atlético."],
    ["Enzo Fernández","El Comandante","Volante argentino elegido mejor jugador joven del Mundial 2022."],
    ["Alexis Mac Allister","El Colo","Volante argentino campeón del mundo, clave en el mediocampo del Liverpool."],
    ["Rodrigo De Paul","El Motorcito","Volante argentino incansable, socio inseparable de Messi en la selección campeona."],
    ["Nicolás Otamendi","El Kun de Hierro","Defensor central argentino, pilar de la Argentina campeona del mundo 2022."],
    ["Emiliano Martínez","El Dibu","Arquero argentino héroe de los penales en la final del Mundial 2022."],
    ["Cristian Romero","El Cuti","Defensor argentino, referente de la zaga campeona del mundo con la Albiceleste."],
    ["Lautaro Martínez","El Toro","Delantero argentino goleador del Inter de Milán y de la selección campeona del mundo."],
    ["Marcus Thuram","El Hijo del Campeón","Delantero francés, hijo de Lilian Thuram, estrella del Inter de Milán."],
    ["Ederson Moraes","El Arquero Futbolista","Arquero brasileño famoso por su capacidad de pase largo, clave en el Manchester City."],
    ["Antonio Rüdiger","El Muro Alemán","Defensor central alemán, ganador de Champions League con dos clubes distintos."],
    ["Declan Rice","El Capitán Joven","Volante inglés, fichaje récord del Arsenal proveniente del West Ham."],
    ["Kai Havertz","El Elegante Alemán","Delantero alemán que anotó el gol decisivo en una final de Champions League."],
    ["Nico Williams","El Rayo de Bilbao","Extremo español, figura clave en el título de la Eurocopa 2024."],
    ["Dani Olmo","El Goleador Inesperado","Volante español, máximo goleador de la Eurocopa 2024 con la Roja."],
    ["Victor Osimhen","El Rey de Nápoles","Delantero nigeriano que llevó al Napoli a ganar el título de Italia después de mucho tiempo."],
    ["Mohammed Kudus","El Ghanés Elegante","Delantero ghanés conocido por su festejo de gol con volteretas."],
    ["Randal Kolo Muani","El Cazador Francés","Delantero francés veloz, protagonista de finales de Copas del Mundo y clubes."],
    ["William Saliba","El Muro Francés","Defensor central francés, pieza clave del resurgir del Arsenal."],
    ["Aurélien Tchouaméni","El Todoterreno Francés","Volante francés, pieza clave del mediocampo del Real Madrid."],
    ["Eduardo Camavinga","El Niño Prodigio Francés","Volante francés que debutó como profesional siendo apenas un adolescente."],
    ["Bruno Fernandes","El Capitán Portugués","Volante portugués, capitán y goleador desde el mediocampo del Manchester United."],
    ["João Félix","El Niño de Oro Portugués","Delantero portugués que fue una de las transferencias más caras de la historia."],
    ["Rafael Leão","El Rayo Portugués","Extremo portugués veloz, referente goleador del Milan."],
    ["Ousmane Dembélé","El Extremo Francés","Delantero francés de gran velocidad, estrella del PSG y antes del Barça."],
    ["Khvicha Kvaratskhelia","Kvaradona","Extremo georgiano cuyo apodo lo compara directamente con Maradona por su gambeta."],
    ["Jamal Musiala","El Mago del Bayern","Volante alemán de gran categoría técnica, formado en la cantera del Chelsea."],
    ["Alphonso Davies","El Rayo Canadiense","Lateral izquierdo canadiense, uno de los más veloces del fútbol mundial."],
    ["Raphinha","El Brasileño de Barcelona","Extremo brasileño, referente ofensivo del Barça en los últimos años."],
    ["Bernardo Silva","El Cerebrito Portugués","Volante portugués de gran talento técnico, pieza clave del Manchester City campeón."],
    ["Nicolò Barella","El Motor Italiano","Volante italiano incansable, referente del Inter de Milán campeón."],
    ["Federico Chiesa","El Hijo del Fútbol Italiano","Extremo italiano, campeón de la Eurocopa 2021 con la Azzurra."],
    ["Fabinho","El Muro Brasileño","Volante defensivo brasileño, pieza clave del Liverpool campeón de todo."],
    ["Gabriel Jesus","El Niño de Oro de Brasil","Delantero brasileño referente ofensivo del Manchester City y luego del Arsenal."],
    ["Richarlison","El Pumba","Delantero brasileño conocido por su festejo imitando a un jabalí."],
    ["Marc-André ter Stegen","El Muro Alemán del Barça","Arquero alemán, titular indiscutido del FC Barcelona durante más de una década."],
    ["Thibaut Courtois","El Gigante Belga","Arquero belga, figura decisiva en varias finales de Champions League con el Real Madrid."],
    ["Romelu Lukaku","El Tanque Belga","Delantero belga potente, máximo goleador histórico de su selección."],
    ["Eden Hazard","El Mago de Bélgica","Extremo belga de gran categoría, ídolo del Chelsea antes de su paso al Real Madrid."],
    ["Ivan Perišić","El Ala Croata","Extremo croata, subcampeón del mundo con Croacia en 2018."],
    ["Mateo Kovačić","El Motor Croata","Volante croata de gran técnica, campeón de Champions League con varios clubes."],
    ["Marcelo Brozović","El Cerebro Croata","Volante croata de gran técnica, pieza clave del mediocampo del Inter de Milán durante años."]
  ],

  medio: [
    ["Andrea Pirlo","El Arquitecto","Definía penales con la 'cucharita' sin ningún nervio."],
    ["Carlos Valderrama","El Pibe","Jugaba con un peinado afro imposible de no reconocer."],
    ["Hristo Stoichkov","El Loco","Uno de los delanteros más temperamentales de los 90."],
    ["Eric Cantona","El Rey","Le dio una patada voladora a un hincha rival y lo suspendieron meses."],
    ["Sócrates","El Doctor","Era médico recibido y capitán del Brasil de la 'Democracia Corinthiana'."],
    ["Michel Platini","Le Roi","Ganó tres Balones de Oro seguidos en los 80."],
    ["Marco van Basten","El Cisne","Metió una volea imposible en la final de la Eurocopa 88."],
    ["Ruud Gullit","El Rasta","Con sus rastas fue el símbolo del Milan campeón de Europa."],
    ["Ferenc Puskás","El Cañoncito","Terminó su carrera con más de 700 goles."],
    ["Alfredo Di Stéfano","La Saeta Rubia","Ganó las primeras cinco Copas de Europa con el Real Madrid."],
    ["Gerd Müller","Der Bomber","Sigue siendo uno de los máximos goleadores de la historia alemana."],
    ["Roberto Carlos","El Misil","Metió un tiro libre que pareció desafiar la física."],
    ["Kaká","El Elegido","Ganó el Balón de Oro en 2007 antes de la era Messi-Cristiano."],
    ["Rodri","El Metrónomo","Ganó el Balón de Oro 2024 jugando de volante central."],
    ["Mesut Özil","El Mago Silencioso","Campeón del mundo 2014 con Alemania."],
    ["Philipp Lahm","El Capitán Perfecto","Levantó la Copa del Mundo 2014 como capitán de Alemania."],
    ["Arjen Robben","El Zurdo Imparable","Su gambeta hacia adentro era un secreto a voces y nadie podía pararla."],
    ["Wesley Sneijder","El Enano Maravilla","Llegó a semis o finales de todo lo que jugó en 2010."],
    ["Ruud van Nistelrooy","El Killer","Uno de los delanteros más letales del Manchester United."],
    ["Luís Figo","El Traidor","Pasó del Barça al Real Madrid y le tiraron una cabeza de cerdo."],
    ["Eusébio","La Pantera Negra","Máximo goleador del Mundial 1966 con Portugal."],
    ["Gabriel Batistuta","Batigol","Metió tripletes en dos Mundiales distintos."],
    ["Mario Kempes","El Matador","Máximo goleador del Mundial 78, ganado por Argentina."],
    ["Juan Román Riquelme","El Último Diez","Jugaba al ritmo que él quería, no al del partido."],
    ["Gonzalo Higuaín","El Pipita","Convirtió un gol clave para Argentina en la final del Mundial 2014."],
    ["James Rodríguez","El 10 Cafetero","Máximo goleador del Mundial 2014 con un golazo de volea."],
    ["Radamel Falcao","El Tigre","Uno de los delanteros más letales de Sudamérica en Europa."],
    ["Iván Zamorano","Bam Bam","Usaba la camiseta con el número '1+8' cuando le sacaron la 9."],
    ["Marcelo Salas","El Matador Chileno","Ídolo histórico de la selección de Chile."],
    ["Zico","El Pelé Blanco","Referente absoluto del Brasil de los 80."],
    ["Rivaldo","El Zurdo Mágico","Metió una chilena inolvidable con el Barça en 2001."],
    ["Cafu","El Pendejo Terrible","Único jugador en jugar tres finales de Mundial consecutivas."],
    ["George Weah","El Rey de África","Único africano en ganar el Balón de Oro."],
    ["Yaya Touré","El Gigante de Costa de Marfil","Ganó cuatro Balones de Oro africanos seguidos."],
    ["Riyad Mahrez","El Argelino Mágico","Campeón sorpresa de la Premier League con el Leicester."],
    ["Achraf Hakimi","El Rayo Marroquí","Llevó a Marruecos a semifinales de un Mundial por primera vez."],
    ["Son Heung-min","El Sónico","Primer asiático en ser máximo goleador de la Premier League."],
    ["Hidetoshi Nakata","El Samurái","Primer futbolista japonés en brillar en la Serie A italiana."],
    ["Landon Donovan","El Ídolo Americano","Máximo goleador histórico de la selección de Estados Unidos."],
    ["Alessandro Del Piero","Pinturicchio","Ídolo eterno de la Juventus con un gol de tijera inolvidable."],
    ["Francesco Totti","El Emperador","Jugó toda su carrera en un solo club, la Roma."],
    ["Fabio Cannavaro","El Pequeño Gigante","Único defensor en ganar el Balón de Oro en el siglo XXI."],
    ["Christian Vieri","Bobo","Uno de los delanteros más caros de la historia en su momento."],
    ["Marco Materazzi","El Provocador","Su comentario terminó con el cabezazo más famoso de la historia."],
    ["Manuel Neuer","El Arquero Líbero","Reinventó la posición jugando casi como un defensor más."],
    ["Lev Yashin","La Araña Negra","Único arquero en ganar un Balón de Oro."],
    ["Miroslav Klose","El Cazador","Máximo goleador histórico en Mundiales."],
    ["Peter Schmeichel","El Muro Danés","Uno de los arqueros más dominantes de los 90."],
    ["Romário","El Baixinho","Formó junto a Bebeto una de las duplas más letales de los 90."],
    ["Hugo Sánchez","El Niño de Oro","Popularizó el remate de chilena en el fútbol español."],
    ["Michael Laudrup","El Danés Elegante","Considerado uno de los mejores jugadores nunca campeones del mundo."],
    ["Gheorghe Hagi","El Maradona de los Cárpatos","Ídolo absoluto del fútbol rumano."],
    ["Davor Šuker","El Zorro de Zagreb","Máximo goleador del Mundial 1998 con Croacia."],
    ["Andriy Shevchenko","Sheva","Ganó el Balón de Oro con el Milan en 2004."],
    ["Pavel Nedvěd","El Furia Checa","Ganó el Balón de Oro jugando para la Juventus."],
    ["Paul Gascoigne","Gazza","Lloró en un Mundial y se hizo ídolo eterno de Inglaterra."],
    ["Gary Lineker","El Caballero Inglés","Nunca recibió una tarjeta en toda su carrera."],
    ["Bebeto","El Festejo de la Cuna","Su festejo de gol imitando una cuna se hizo mundialmente famoso."],
    ["Clint Dempsey","Deuce","Referente del fútbol estadounidense en varios Mundiales."],
    ["Tim Howard","El Muro","Hizo una cantidad récord de atajadas en un Mundial."],
    ["Diego Simeone","El Cholo","Volante argentino de carácter feroz, hoy leyenda como entrenador del Atlético."],
    ["Fernando Redondo","El Príncipe de la Melena","Volante elegante argentino recordado por un caño imposible en Champions League."],
    ["Ariel Ortega","El Burrito","Enganche argentino de gambeta endiablada en los 90."],
    ["Hernán Crespo","El Valdanito","Delantero argentino prolífico en el Inter, Lazio y Chelsea."],
    ["Javier Saviola","El Conejo","Delantero argentino que brilló joven en River y luego en el Barça."],
    ["Juan Sebastián Verón","La Brujita","Volante argentino, uno de los fichajes más caros de su época en Inglaterra."],
    ["Walter Samuel","El Muro","Defensor argentino pilar de la defensa del Inter campeón de todo en 2010."],
    ["Roberto Ayala","El Ratón","Defensor central, capitán de la selección argentina en los 2000."],
    ["Iván Córdoba","El Muro Cafetero","Defensor colombiano, capitán histórico del Inter de Milán."],
    ["Faryd Mondragón","El Arquero Eterno","Se convirtió en el jugador más veterano en jugar un Mundial con Colombia en 2014."],
    ["Faustino Asprilla","El Tino","Delantero colombiano recordado por un hat-trick con el Newcastle contra el Barça."],
    ["René Higuita","El Loco","Arquero colombiano inventor de la 'jugada del escorpión'."],
    ["Freddy Rincón","El Coloso del Pacífico","Volante colombiano histórico de la selección de los 90."],
    ["Enner Valencia","El Capitán Ecuatoriano","Delantero, referente goleador de Ecuador en varios Mundiales."],
    ["Antonio Valencia","El Toño","Lateral y extremo ecuatoriano, capitán del Manchester United."],
    ["Máxi Rodríguez","La Fiera","Metió un golazo de volea inolvidable en el Mundial 2006 con Argentina."],
    ["Pablo Aimar","El Payasito","Enganche argentino admirado por Messi en su infancia."],
    ["Nolberto Solano","Ñol","Volante peruano referente del Newcastle a comienzos de los 2000."],
    ["Paolo Guerrero","El Depredador","Capitán histórico de la selección peruana, máximo goleador del equipo."],
    ["Jefferson Farfán","La Foquita","Delantero peruano que brilló en el fútbol alemán."],
    ["Álvaro Recoba","El Chino","Delantero uruguayo de gran pegada con la zurda, ídolo del Inter y Nacional."],
    ["Diego Lugano","El Capitán Guerrero","Defensor central, líder de la 'Garra Charrúa' uruguaya de 2010."],
    ["Sebastián Abreu","El Loco","Definió un penal con un 'panenka' clave para Uruguay en un Mundial."],
    ["Fernando Muslera","El Arquero de Uruguay","Guardameta titular de Uruguay durante más de una década."],
    ["Ivan Rakitić","El Croata del Barça","Volante clave del Barça que ganó un triplete y fue subcampeón del mundo."],
    ["Dejan Stanković","El Duja","Volante serbio, jugó Mundiales con tres selecciones distintas antes de la separación yugoslava."],
    ["Nemanja Vidić","El Capitán Serbio","Defensor central, pilar de la defensa del Manchester United."],
    ["Branislav Ivanović","El Muro Serbio","Defensor y lateral, referente del Chelsea campeón de Champions."],
    ["Robert Prosinečki","El Mozart Croata","Volante creativo, parte de la 'generación dorada' croata de 1998."],
    ["Zvonimir Boban","El Capitán Croata","Símbolo del fútbol croata, protagonizó un incidente histórico con la policía en 1990."],
    ["Slaven Bilić","El Rockero Croata","Defensor croata que también tocaba en una banda de rock."],
    ["Edin Džeko","El Cisne de Sarajevo","Delantero bosnio, referente goleador del Manchester City y la Roma."],
    ["Miralem Pjanić","El Elegante Bosnio","Volante de gran pegada en tiros libres, ídolo de la Roma y la Juventus."],
    ["Asmir Begović","El Arquero Récord","Arquero bosnio que metió un gol desde su propio arco en la Premier League."],
    ["Milan Baroš","El Delantero Checo","Máximo goleador de la Eurocopa 2004 con República Checa."],
    ["Tomáš Rosický","El Mozart Checo","Volante checo, ídolo del Arsenal por su técnica y visión de juego."],
    ["Jan Koller","El Gigante Checo","Delantero altísimo, referente goleador de la selección checa."],
    ["Marek Hamšík","El Capitán Eslovaco","Máximo goleador histórico del Napoli antes de la era Osimhen."],
    ["Jakub Błaszczykowski","Kuba","Extremo polaco, capitán de su selección durante varios años."],
    ["Zbigniew Boniek","Zibi","Delantero polaco, uno de los mejores futbolistas europeos de comienzos de los 80."],
    ["Ronald Koeman","El Cañonero Holandés","Defensor con gran pegada, metió el gol que le dio al Barça su primera Copa de Europa en 1992."],
    ["Frank Rijkaard","El Elegante Holandés","Parte del histórico Milan de 'los tres holandeses', luego DT campeón con el Barça."],
    ["Patrick Kluivert","El Killer Holandés","Delantero neerlandés, máximo goleador histórico de su selección durante años."],
    ["Robin van Persie","El Cisne Volador","Delantero neerlandés recordado por un cabezazo volador contra España en el Mundial 2014."],
    ["Nigel de Jong","El Destructor","Volante holandés temido por la dureza de sus entradas."],
    ["Mark van Bommel","El Capitán Aguerrido","Volante holandés de carácter fuerte, capitán en Bayern y selección."],
    ["Giovanni van Bronckhorst","Gio","Lateral y capitán de Holanda en la final del Mundial 2010."],
    ["Memphis Depay","El Artista Holandés","Delantero neerlandés reconocido también por su faceta como músico."],
    ["Georginio Wijnaldum","Gini","Volante box-to-box, clave en el título de Champions del Liverpool."],
    ["Frenkie de Jong","El Ajedrecista Holandés","Volante de salida elegante, referente del Ajax y luego del Barça."],
    ["Matthijs de Ligt","El Capitán Adolescente","Fue capitán del Ajax en semifinales de Champions siendo casi un adolescente."],
    ["Emilio Butragueño","El Buitre","Delantero español, líder de la 'Quinta del Buitre' del Real Madrid en los 80."],
    ["Míchel González","El Otro Buitre","Volante clave de la 'Quinta del Buitre' madridista."],
    ["Andoni Zubizarreta","Zubi","Arquero español con más partidos jugados en la historia de la Liga."],
    ["Pep Guardiola","El Jugador que Dirigía","Antes de ser entrenador legendario, fue el cerebro del Barça de los 90."],
    ["Fernando Hierro","El Capitán de Hierro","Defensor central, capitán histórico de la selección española."],
    ["Santi Cañizares","El Arquero Elegante","Guardameta español titular en Valencia y varias selecciones."],
    ["Joaquín Sánchez","El Eterno de Cádiz","Extremo español que jugó en Primera División hasta pasados los 40 años."],
    ["David Silva","El Mago Malagueño","Volante clave del Manchester City en su era dorada."],
    ["Juan Mata","El Caballero del Fútbol","Ganó premios por su solidaridad además de dos títulos de Premier League distintos."],
    ["Cesc Fàbregas","El Capitán Adolescente del Arsenal","Fue capitán del Arsenal siendo apenas un veinteañero."],
    ["Isco","El Mago de Málaga","Volante español de gran categoría técnica en el Real Madrid de las tres Champions seguidas."],
    ["Álvaro Morata","El 9 Español","Delantero español, referente de la selección en varias Eurocopas."],
    ["Diego Costa","El Guerrero","Delantero nacido en Brasil que se nacionalizó español para jugar la Roja."],
    ["Pedro Rodríguez","Pedrito","Delantero español, pieza clave del histórico sextete del Barça en 2009."],
    ["Santi Cazorla","El Mago de Oviedo","Volante español admirado por su categoría técnica pese a su baja estatura."],
    ["Rafael Márquez","El Káiser Mexicano","Capitán histórico de México, jugó cinco Copas del Mundo."],
    ["Cuauhtémoc Blanco","El Cuau","Ídolo mexicano famoso por su regate 'la cuauhtemiña'."],
    ["Javier Hernández","Chicharito","Delantero mexicano, máximo goleador histórico de su selección."],
    ["Andrés Guardado","El Principito","Volante mexicano con récord de participaciones en Copas del Mundo."],
    ["Claudio Suárez","El Emperador","Defensor mexicano con más partidos jugados en la historia de su selección."],
    ["DaMarcus Beasley","El Estadounidense Viajero","Jugó cuatro Copas del Mundo distintas con Estados Unidos."],
    ["Christian Pulisic","Captain America","Delantero estadounidense, referente de su selección en el Chelsea."],
    ["Kolo Touré","El Muro Marfileño","Defensor central, parte del Arsenal invicto en la Premier League."],
    ["Emmanuel Adebayor","Sheyi","Delantero togolés goleador que brilló en el Arsenal y Manchester City."],
    ["Jay-Jay Okocha","El Mago Nigeriano","Volante nigeriano famoso por sus gambetas imposibles."],
    ["Nwankwo Kanu","El Zurdo Nigeriano","Delantero nigeriano campeón olímpico y bicampeón de Champions League."],
    ["Rigobert Song","El Capitán de Camerún","Jugó ocho Copas de África distintas con la selección camerunesa."],
    ["Sunday Oliseh","El Volante de Hierro","Metió un golazo histórico de volea contra España en el Mundial 98."],
    ["El Hadji Diouf","El Provocador Senegalés","Delantero clave en la histórica clasificación de Senegal al Mundial 2002."],
    ["Frédéric Kanouté","El Elegante de Malí","Delantero franco-maliense, ídolo del Sevilla en sus títulos europeos."],
    ["Michael Essien","El Bisonte","Volante ghanés temido por su potencia física, ídolo del Chelsea."],
    ["Asamoah Gyan","El Rey de Ghana","Máximo goleador histórico de África en Copas del Mundo."],
    ["Park Ji-sung","El Motor Surcoreano","Volante incansable, primer asiático en ganar la Champions League."],
    ["Keisuke Honda","El Samurái Frío","Volante japonés reconocido por su gran pegada en tiros libres."],
    ["Shinji Kagawa","El Diez Japonés","Volante japonés que brilló en el Borussia Dortmund y Manchester United."],
    ["Tim Cahill","El Cabeceador Australiano","Delantero australiano famoso por sus goles de cabeza y festejo de boxeo."],
    ["Harry Kewell","El Australiano de Leeds","Extremo australiano estrella del Leeds United a comienzos de los 2000."],
    ["Mark Viduka","El Capitán de Oceanía","Delantero australiano, capitán y goleador histórico de su selección."],
    ["Brad Friedel","El Arquero de Hierro","Arquero estadounidense que jugó más de 300 partidos consecutivos en la Premier League."],
    ["André Carrillo","La Culebra","Extremo peruano, referente ofensivo de la selección en el Mundial 2018."],
    ["Renato Tapia","El Capitán del Mediocampo","Volante peruano, pieza clave y capitán de la selección en los últimos años."],
    ["Yoshimar Yotún","El Capitán Cremita","Volante peruano, capitán histórico de Sporting Cristal y referente de la selección."],
    ["Christian Cueva","Aladino","Volante ofensivo peruano de gran categoría técnica, ídolo en varios clubes del continente."],
    ["Miguel Trauco","El Lateral Peruano","Defensor peruano zurdo, titular en la selección durante el ciclo del Mundial 2018."],
    ["Luis Advíncula","El Rayo","Lateral derecho peruano, uno de los más veloces de la selección."],
    ["Alexander Callens","El Muro Peruano","Defensor central peruano, referente de la zaga de la selección en Sudamérica."],
    ["Pedro Gallese","El Pulpo","Arquero peruano titular en el histórico regreso de Perú a un Mundial en 2018."],
    ["Roberto Palacios","El Chorri","Volante peruano de gambeta habilidosa, ídolo histórico de Universitario y Sporting Cristal."],
    ["Carlos Zambrano","El León","Defensor central peruano, referente físico y de carácter de la selección."],
    ["Wilder Cartagena","El Warrior","Volante contenedor peruano, pieza clave del mediocampo defensivo de la selección."],
    ["Gianluca Lapadula","El Bambino","Delantero peruano-italiano, máximo referente goleador de la selección en años recientes."],
    ["Edison Flores","El Orejas","Delantero peruano, uno de los goleadores de la selección en la era de Ricardo Gareca."],
    ["Ever Banega","El Pulga del Pase","Volante argentino de gran técnica, campeón de la Europa League en varias ocasiones."],
    ["Gonzalo Montiel","Cachete","Lateral argentino que convirtió el penal decisivo en la final del Mundial 2022."],
    ["Marcos Acuña","El Huevo","Lateral izquierdo argentino, campeón del mundo en 2022."],
    ["Esteban Cambiasso","El Cuchu","Volante argentino, pieza clave del Inter que ganó el triplete en 2010."],
    ["Diego Milito","El Príncipe","Delantero argentino que marcó los dos goles de la final de Champions League 2010."],
    ["Paulo Dybala","La Joya","Delantero argentino de gran categoría técnica, ídolo de la Juventus y la Roma."],
    ["Marquinhos","El Capitán de Brasil en París","Defensor central brasileño, capitán histórico del PSG."],
    ["Philippe Coutinho","El Mago de Río","Volante brasileño que fue una de las transferencias más caras de la historia del fútbol."],
    ["Willian","El Extremo Brasileño","Extremo brasileño de gran regularidad, referente ofensivo del Chelsea durante años."],
    ["Fernandinho","El Capitán Silencioso","Volante defensivo brasileño, pieza clave del Manchester City en su era dorada."],
    ["Hulk","El Toro Brasileño","Delantero brasileño de gran potencia física, conocido por sus disparos de larga distancia."],
    ["Oscar","El Diez de Brasil","Volante ofensivo brasileño que brilló en el Chelsea antes de irse al fútbol chino."],
    ["Granit Xhaka","El Capitán Suizo","Volante suizo de carácter fuerte, capitán del Arsenal antes de brillar en Alemania."],
    ["Manuel Akanji","El Muro Suizo","Defensor central suizo, campeón de la Champions League con el Manchester City."],
    ["Piotr Zieliński","El Cerebro Polaco","Volante polaco de gran categoría técnica, referente del Napoli campeón de Italia."],
    ["Wojciech Szczęsny","El Arquero Polaco","Arquero polaco, titular durante años en la Juventus."],
    ["Kasper Schmeichel","El Hijo del Gigante","Arquero danés, héroe del título milagroso del Leicester City en la Premier League."],
    ["Christian Eriksen","El Mago Danés","Volante danés de gran pegada, sobrevivió a un paro cardíaco en plena Eurocopa y volvió a jugar."],
    ["Simon Kjær","El Capitán que Ayudó","Defensor danés recordado por auxiliar a su compañero Eriksen durante su emergencia médica."],
    ["Pierre-Emerick Aubameyang","El Depredador Gabonés","Delantero gabonés, uno de los goleadores más letales de la Premier League en su época."],
    ["Ademola Lookman","El Héroe de la Europa League","Delantero nigeriano que anotó un triplete en la final de la Europa League con el Atalanta."],
    ["André Onana","El Arquero Camerunés","Arquero camerunés, titular en el Inter de Milán y luego en el Manchester United."],
    ["Rafael van der Vaart","El Elegante Holandés","Volante ofensivo neerlandés de gran técnica, ídolo del Real Madrid y el Tottenham."],
    ["Klaas-Jan Huntelaar","El Cazador Holandés","Delantero neerlandés, máximo goleador histórico del Ajax en la era moderna."],
    ["Dirk Kuyt","El Trabajador Incansable","Delantero holandés recordado por su entrega total con la camiseta del Liverpool."],
    ["Ashley Cole","El Lateral de Hierro","Lateral izquierdo inglés, considerado uno de los mejores de su posición en la historia de la Premier League."],
    ["Rio Ferdinand","El Defensor Elegante","Defensor central inglés, pilar de la defensa del Manchester United durante una década."],
    ["Gary Neville","El Capitán del United","Lateral derecho inglés, referente y capitán del Manchester United en los 2000."],
    ["Jamie Carragher","El Corazón de Liverpool","Defensor inglés que jugó toda su carrera profesional en un solo club, el Liverpool."],
    ["Nemanja Matić","El Muro Serbio del United","Volante defensivo serbio, campeón de la Premier League con dos clubes distintos."],
    ["Wesley Fofana","El Defensor Francés","Defensor central francés, fichaje destacado del Chelsea proveniente del Leicester."],
    ["Wilfried Zaha","El Rey de Selhurst Park","Extremo marfileño, ídolo histórico del Crystal Palace."],
    ["Jack Wilshere","La Promesa Rota","Volante inglés considerado una de las mayores promesas de su generación antes de las lesiones."],
    ["Theo Walcott","El Velocista del Arsenal","Extremo inglés conocido por su gran velocidad, debutó en Primera siendo casi un adolescente."],
    ["Raheem Sterling","El Chico de Londres","Delantero inglés, referente ofensivo del Manchester City en su era más dominante."],
    ["Danny Welbeck","El Delantero Versátil","Delantero inglés que jugó tanto en el Manchester United como en el Arsenal."],
    ["Aaron Ramsey","El Galés del Arsenal","Volante galés recordado por marcar goles decisivos en finales de la FA Cup."],
    ["Joe Cole","El Talento de West Ham","Volante ofensivo inglés de gran categoría técnica, campeón de Champions League con el Chelsea."],
    ["Ledley King","El Defensor sin Rodillas","Defensor inglés del Tottenham que jugó gran parte de su carrera con serios problemas físicos."],
    ["Sol Campbell","El Defensor de las Dos Camisetas","Defensor inglés que pasó del Tottenham al Arsenal, algo históricamente polémico en Londres."],
    ["Robert Huth","El Campeón Sorpresa","Defensor alemán, parte del milagroso título de Premier League del Leicester City."],
    ["Filippo Inzaghi","Súper Pippo","Delantero italiano famoso por su habilidad para estar siempre en posición de gol."],
    ["Micah Richards","El Defensor que Ahora Hace Reír","Defensor inglés del Manchester City, hoy muy popular como comentarista de televisión."],
    ["Naby Keïta","El Motor Guineano","Volante guineano de gran despliegue físico, referente del Liverpool durante varias temporadas."],
    ["Idrissa Gueye","El Destructor Senegalés","Volante defensivo senegalés temido por la dureza y precisión de sus entradas."],
    ["Wilfred Ndidi","El Muro Nigeriano","Volante defensivo nigeriano, uno de los que más balones recupera en la Premier League."],
    ["Alex Iwobi","El Nigeriano de Londres","Delantero nigeriano formado en la cantera del Arsenal, sobrino de Jay-Jay Okocha."],
    ["Victor Wanyama","El Muro de Kenia","Volante keniano, referente defensivo del Southampton y el Tottenham."],
    ["Mohamed Elneny","El Farmacéutico Egipcio","Volante egipcio del Arsenal, apodado así porque estudió Farmacia antes de ser futbolista."],
    ["Hakim Ziyech","El Mago Marroquí","Volante ofensivo marroquí, clave en la histórica semifinal de Marruecos en el Mundial 2022."],
    ["Sofyan Amrabat","El Motor Marroquí","Volante marroquí, pieza clave del mediocampo en el histórico Mundial 2022 de su selección."],
    ["Yassine Bounou","Bono","Arquero marroquí, héroe de penales en el camino de Marruecos a semifinales del Mundial 2022."],
    ["Kalidou Koulibaly","El Muro Senegalés","Defensor central senegalés, uno de los más sólidos de la Serie A durante años en el Napoli."],
    ["Takefusa Kubo","El Messi Japonés","Delantero japonés de gran categoría técnica, formado en la cantera del Barcelona."],
    ["Wataru Endo","El Capitán de Japón","Volante defensivo japonés, capitán de la selección nipona en Mundiales recientes."],
    ["Hwang Hee-chan","El Delantero Surcoreano","Delantero surcoreano, referente ofensivo del Wolverhampton en la Premier League."],
    ["Kim Min-jae","El Monstruo Surcoreano","Defensor central surcoreano, campeón de Italia con el Napoli antes de fichar por el Bayern Múnich."]
  ],

  dificil: [
    ["Roberto Rivellino","El Bigote Mágico","Volante zurdo del Brasil campeón en 1970, inventó una finta con la suela que todavía se enseña en escuelas de fútbol de todo el mundo."],
    ["Tostão","El Pelé Blanco de Minas","Delantero brasileño pieza clave del ataque campeón del Mundial 1970, se retiró joven por problemas de visión y luego se hizo médico oftalmólogo."],
    ["Jairzinho","El Huracán","Único jugador en convertir en todos los partidos de una misma Copa del Mundo, la de 1970 con Brasil."],
    ["Just Fontaine","El Récord Eterno","Delantero francés que metió 13 goles en el Mundial de 1958, un récord de goleo en un solo Mundial que sigue vigente."],
    ["Raymond Kopa","El Napoleón del Fútbol","Primer gran ídolo francés del Real Madrid en los años 50, ganó el Balón de Oro en 1958 y varias Copas de Europa."],
    ["Enzo Francescoli","El Príncipe","Volante uruguayo referente de River Plate, tan admirado que Zinedine Zidane bautizó a su hijo Enzo en su honor."],
    ["Abedi Pelé","El Rey de Ghana","Estrella ghanesa del Olympique de Marsella en los 90, tres veces elegido mejor futbolista de África."],
    ["Roger Milla","El Bailarín del Córner","Delantero camerunés que a los 42 años sigue siendo el goleador más veterano en la historia de los Mundiales, festejaba bailando junto al banderín."],
    ["Brian Laudrup","El Otro Laudrup","Extremo danés, hermano de Michael, elegido mejor jugador extranjero de la Premier League jugando para el Rangers escocés."],
    ["Rui Costa","El Maestro","Volante portugués de pase preciso, ídolo de la Fiorentina antes de brillar en el Milan de comienzos de los 2000."],
    ["Deco","El Brasileño Portugués","Nacido en Brasil pero nacionalizado portugués, fue clave en el Barça de Ronaldinho y en el Oporto campeón de Champions 2004."],
    ["Oleg Blokhin","El Cohete Soviético","Extremo ucraniano velocísimo, ganó el Balón de Oro en 1975 jugando para la Unión Soviética."],
    ["Igor Belanov","El Otro Balón de Oro Soviético","Delantero ucraniano que ganó el Balón de Oro en 1986 tras un Mundial destacado con la URSS."],
    ["Allan Simonsen","El Danés Dinamita","Ganó el Balón de Oro en 1977 pese a medir apenas 1,65 metros, ídolo del Borussia Mönchengladbach."],
    ["Kevin Keegan","El Rubio Volador","Delantero inglés ganador de dos Balones de Oro en los 70, símbolo del Hamburgo alemán antes de volver a Inglaterra."],
    ["Ian Rush","El Galés Letal","Máximo goleador histórico del Liverpool, tan temido que decían que 'jugar contra él era un crimen'."],
    ["Peter Beardsley","El Motorcito","Delantero inglés bajito pero incansable, pieza clave del Liverpool campeón de finales de los 80."],
    ["Bryan Robson","Capitán Marvel","Capitán histórico del Manchester United en los 80, jugaba lesionado con tal de no dejar solo a su equipo."],
    ["Matt Le Tissier","El Rey del Gol Imposible","Delantero inglés que pasó toda su carrera en el Southampton, recordado por goles casi imposibles de gimnasia."],
    ["Preben Elkjær","El Danés de Verona","Delantero danés estrella del Hellas Verona campeón sorpresa de la Serie A en 1985."],
    ["Nílton Santos","El Enciclopedia","Lateral izquierdo brasileño bicampeón del mundo en 1958 y 1962, considerado uno de los inventores del lateral moderno."],
    ["Djalma Santos","El Otro Santos","Lateral derecho brasileño tricampeón del mundo, formó junto a Nílton Santos una dupla defensiva histórica sin parentesco entre ellos."],
    ["Bobby Moore","El Caballero Inglés","Capitán de Inglaterra campeona del Mundial 1966, elegido mejor jugador de ese torneo jugando de defensor."],
    ["Gordon Banks","La Mejor Atajada de la Historia","Arquero inglés autor de una tapada a un cabezazo de Pelé en el Mundial 1970 considerada la mejor atajada de todos los tiempos."],
    ["Geoff Hurst","El Único Triplete en una Final","Delantero inglés, sigue siendo el único jugador en convertir tres goles en una final de Copa del Mundo, la de 1966."],
    ["Sándor Kocsis","Cabeza de Oro","Delantero húngaro de la 'Aranycsapat' de los años 50, tan bueno de cabeza que le decían así por sus remates aéreos."],
    ["Nándor Hidegkuti","El Falso 9 Original","Delantero húngaro que popularizó la posición de 'falso nueve' al humillar a la defensa inglesa en 1953."],
    ["Omar Sívori","El Cabezón","Delantero nacido en Argentina y nacionalizado italiano, ganó el Balón de Oro en 1961 jugando para la Juventus."],
    ["Ladislao Kubala","El Fantasma","Delantero de origen húngaro-checoslovaco, ídolo fundacional del Barça de los años 50, el club le hizo un partido homenaje único en la historia."],
    ["Elías Figueroa","El Zar","Defensor chileno tres veces elegido mejor jugador de Sudamérica en los años 70, considerado el mejor futbolista chileno de la historia."],
    ["Enzo Scifo","El Mozart del Fútbol Belga","Volante creativo belga de los años 80 y 90, brilló en Mundiales con la camiseta de Bélgica."],
    ["Jean-Pierre Papin","JPP","Delantero francés ganador del Balón de Oro en 1991 jugando para el Olympique de Marsella."],
    ["David Ginola","El Galán Francés","Extremo francés de pelo largo, ídolo de culto en la Premier League de los 90 pese a nunca jugar un Mundial."],
    ["Youri Djorkaeff","El Mago Armenio-Francés","Volante clave en el título mundial de Francia 1998, de ascendencia armenia y kalmuca."],
    ["Claude Makélélé","El Hombre Invisible","Volante defensivo francés tan influyente que su posición se bautizó 'el rol de Makélélé' en su honor."],
    ["Edgar Davids","El Pitbull","Volante holandés reconocible por sus lentes protectores, símbolo de la Naranja Mecánica de los 90."],
    ["Clarence Seedorf","El Único Tricampeón con Tres Clubes","Único futbolista en ganar la Champions League con tres equipos distintos: Ajax, Real Madrid y Milan."],
    ["Emile Heskey","El Complemento Perfecto","Delantero inglés que rara vez metía goles pero cuyos compañeros insistían en que 'jugaba mejor todo el equipo' con él en cancha."],
    ["Robbie Fowler","El Dios de Anfield","Delantero inglés uno de los más rápidos en llegar a 100 goles en la Premier League, ídolo absoluto del Liverpool."],
    ["Teddy Sheringham","El Tramposo Genial","Delantero inglés de gran inteligencia táctica, campeón de la Champions con el United en el último minuto en 1999."],
    ["Les Ferdinand","Sir Les","Delantero inglés potente y goleador, referente del Newcastle y Queens Park Rangers en los 90."],
    ["Nelinho","El Banana","Lateral brasileño autor de un histórico tiro libre con efecto imposible en el Mundial 1978."],
    ["Paulo Roberto Falcão","El Rey de Roma","Volante brasileño de la 'Democracia Corinthiana', ídolo absoluto de la AS Roma pese a nunca ganar un Mundial."],
    ["Éder","El de la Chilena Imposible","Delantero brasileño autor de un golazo de chilena recordado en el Mundial 1982."],
    ["Careca","El Socio de Maradona","Delantero brasileño que formó junto a Maradona un ataque temible en el Napoli campeón de Italia."],
    ["Dunga","El Capitán Incomprendido","Capitán de Brasil campeón del Mundial 1994, muy criticado en su país por su estilo poco vistoso."],
    ["Taffarel","El Héroe de los Penales","Arquero brasileño que atajó penales decisivos en la final del Mundial 1994."],
    ["Roberto Dinamite","El Ídolo de Vasco da Gama","Máximo goleador histórico del club Vasco da Gama en Brasil, ídolo total de su hinchada."],
    ["Ubaldo Fillol","El Pato","Arquero argentino campeón del Mundial 1978, considerado de los mejores de la historia de su país."],
    ["Daniel Passarella","El Gran Capitán","Defensor y capitán de Argentina campeona del Mundial 1978, poco habitual como defensor goleador."],
    ["Osvaldo Ardiles","Ossie","Volante argentino campeón del Mundial 1978, luego ídolo en el Tottenham inglés."],
    ["Ricardo Bochini","El Bocha","Enganche argentino de Independiente, admitido por el propio Maradona como su ídolo futbolístico."],
    ["José Luis Chilavert","El Loco Chilavert","Arquero paraguayo que convertía goles de penal y tiro libre, algo insólito para su posición."],
    ["Roque Santa Cruz","El Tanque Paraguayo","Delantero paraguayo referente goleador de su selección en los años 2000."],
    ["Arsenio Erico","El Rey del Gol Sudamericano","Delantero paraguayo, máximo goleador histórico del fútbol argentino, en los años 30 y 40."],
    ["Héctor Scarone","El Mago","Delantero uruguayo bicampeón olímpico en los años 20, ídolo fundacional de Nacional."],
    ["José Nasazzi","El Mariscal","Capitán de Uruguay, campeón del primer Mundial de la historia en 1930."],
    ["Obdulio Varela","El Negro Jefe","Capitán uruguayo del histórico 'Maracanazo', silenció a todo un estadio de Brasil en 1950."],
    ["Alcides Ghiggia","El Silenciador de Maracaná","Autor del gol que le dio a Uruguay el Mundial 1950 ante el local Brasil."],
    ["Juan Alberto Schiaffino","Pepe","Volante uruguayo campeón del Mundial 1950, luego estrella en Italia."],
    ["Carlos Caszely","El Rey del Metro Cuadrado","Delantero chileno estrella del Mundial 1974, siempre un símbolo de resistencia política en su país."],
    ["Leonel Sánchez","El Zurdo de Oro","Delantero chileno, máximo goleador del Mundial 1962 disputado en su propio país."],
    ["Hugo Sotil","El Cholo Sotil","Delantero peruano que formó dupla goleadora con Cruyff en el Barça de los 70."],
    ["József Bozsik","El Diplomático del Fútbol","Volante húngaro de la 'Aranycsapat', también fue diputado en el parlamento de su país."],
    ["Igor Netto","El Capitán Soviético","Capitán de la URSS campeona de la primera Eurocopa de la historia en 1960."],
    ["Rinat Dasayev","La Araña de Moscú","Arquero soviético considerado uno de los mejores del mundo en los años 80."],
    ["Grzegorz Lato","El Rayo Polaco","Máximo goleador del Mundial 1974, disputado por una sorprendente Polonia."],
    ["Włodzimierz Lubański","El Cañón Polaco","Delantero polaco de los 60 y 70, su carrera se vio marcada por una grave lesión en un Mundial."],
    ["Dragan Džajić","El Mejor Yugoslavo de Todos los Tiempos","Extremo yugoslavo, ídolo eterno del Estrella Roja de Belgrado."],
    ["Safet Sušić","El Mago de Sarajevo","Volante yugoslavo-bosnio de gran categoría técnica, ídolo del PSG en los 80."],
    ["Krasimir Balakov","El Mago Búlgaro","Volante clave de la histórica Bulgaria semifinalista del Mundial 1994."],
    ["Henrik Larsson","El Rey de Glasgow","Delantero sueco, ídolo absoluto del Celtic antes de brillar también en el Barça."],
    ["Ole Gunnar Solskjær","El Asesino de Cara de Bebé","Delantero noruego suplente que metió el gol del título de Champions en el último minuto en 1999."],
    ["Roy Keane","El Capitán de Hierro","Volante irlandés de carácter feroz, capitán histórico del Manchester United."],
    ["Paul McGrath","El Dios Negro de Irlanda","Defensor irlandés considerado uno de los mejores de la historia de su selección."],
    ["Kenny Dalglish","El Rey Kenny","Delantero escocés, ídolo absoluto del Liverpool como jugador y luego como entrenador."],
    ["Denis Law","El Rey de Old Trafford","Delantero escocés, único ganador del Balón de Oro en la historia de su selección."],
    ["Rabah Madjer","El de la Taquita Histórica","Delantero argelino autor de un gol de taco inolvidable en la final de la Copa de Europa 1987."],
    ["Lakhdar Belloumi","El Mago Argelino","Delantero argelino, estrella de la histórica Argelia que venció a Alemania en el Mundial 1982."],
    ["Thomas N'Kono","El Maestro de los Arqueros","Arquero camerunés que con su estilo inspiró a un joven Gianluigi Buffon."],
    ["Stephen Keshi","El Gran Jefe","Capitán nigeriano campeón de la Copa Africana, luego campeón también como director técnico."],
    ["Rashidi Yekini","El Grito de África","Delantero nigeriano autor de un festejo histórico abrazando la red en el Mundial 1994."],
    ["Kalusha Bwalya","El Rey de Zambia","Considerado el mejor futbolista de la historia de Zambia, ídolo total en su país."],
    ["Mahmoud El-Khatib","Bibo","Delantero egipcio, ídolo histórico del club Al Ahly, uno de los más grandes de África."],
    ["Hossam Hassan","El Faraón Goleador","Delantero egipcio, durante años poseedor del récord de goles con la selección de Egipto."],
    ["Cha Bum-kun","El Pionero Asiático","Delantero surcoreano pionero del fútbol asiático en la Bundesliga alemana de los 80."],
    ["Kazuyoshi Miura","El Rey Kazu","Delantero japonés que a edad avanzada seguía jugando profesionalmente, todo un fenómeno de longevidad."],
    ["Ali Daei","El Cañonero Persa","Delantero iraní que durante años tuvo el récord de goles en selecciones a nivel mundial."],
    ["Saeed Al-Owairan","El Maradona Saudí","Autor de un gol solitario recorriendo media cancha ante Bélgica en el Mundial 1994."],
    ["Majed Abdullah","El Rey del Fútbol Saudí","Delantero considerado el mejor futbolista de la historia de Arabia Saudita."],
    ["Gunnar Nordahl","El Sueco Goleador","Delantero sueco de los años 50, uno de los máximos goleadores históricos del Milan italiano."],
    ["Nils Liedholm","El Barón","Volante sueco elegante, parte del histórico trío 'Gre-No-Li' del Milan de los 50."],
    ["Larbi Ben Barek","La Perla Negra","Delantero marroquí-francés de los años 30 y 40, pionero africano en Europa."],
    ["Mário Zagallo","El Viejo Lobo","Único hombre en salir campeón del mundo como jugador y como director técnico con Brasil."],
    ["Amarildo","El que Reemplazó a Pelé","Delantero brasileño que sustituyó a un Pelé lesionado y brilló en el Mundial 1962."],
    ["Didi","El de la Hoja Seca","Volante brasileño bicampeón del mundo, inventor del tiro libre 'hoja seca' con efecto imprevisible."],
    ["Vavá","El Doble Finalista","Delantero brasileño, marcó en dos finales de Copa del Mundo consecutivas, 1958 y 1962."],
    ["José Torres","El Gigante de Portugal","Delantero portugués de gran juego aéreo, socio de área de Eusébio en el Mundial 1966."],
    ["Mário Coluna","El Capitán de Mozambique","Capitán de Portugal en el histórico tercer puesto del Mundial 1966, nacido en Mozambique."],
    ["Julio César Uribe","El Diamante","Delantero peruano de gran categoría técnica, ídolo del Sporting Cristal en los años 80."],
    ["Percy Rojas","El Cabezón","Volante peruano de gran pegada, campeón con Perú en la Copa América de 1975."],
    ["José Velásquez","Patrulla 70","Volante peruano, parte del histórico equipo campeón de la Copa América 1975."],
    ["Waldir Sáenz","Diablito","Delantero peruano goleador, referente de Alianza Lima en los años 90 y 2000."],
    ["Flavio Maestri","El Africano","Delantero peruano recordado por su gol de cabeza en el repechaje ante Chile en 1997."],
    ["Guillermo La Rosa","Coco","Delantero peruano, campeón goleador histórico en la liga local en los años 90."],
    ["Eduardo Esidio","El Cacique","Volante y delantero peruano surgido de la cantera de Universitario de Deportes."],
    ["Julio Meléndez","Coto","Defensor peruano, parte de la selección que jugó el Mundial de España 1982."],
    ["Valeriano López","El Zorro","Delantero peruano, ídolo histórico de Alianza Lima en las décadas del 60 y 70."],
    ["César Cueto","El Poeta de la Zurda","Volante peruano de gran técnica, parte de las selecciones de los Mundiales de 1978 y 1982."],
    ["Julio Baylón","El Beto","Delantero peruano, campeón goleador histórico en el fútbol local en los años 70."],
    ["Enrique Casaretto","El Capitán","Defensor peruano, capitán de la selección en el Mundial de Argentina 1978."],
    ["Alejandro Villanueva","El Turco","Delantero peruano de los años 20 y 30, uno de los primeros ídolos del fútbol nacional."],
    ["Eduardo Malásquez","Cachito","Delantero peruano, parte de la selección campeona de la Copa América 1975."],
    ["Franco Navarro","El Tanque","Delantero peruano goleador de las décadas del 80 y 90 en el fútbol local."],
    ["Máximo Mosquera","El Chinito","Volante peruano, parte del histórico plantel campeón de la Copa América 1975."],
    ["Fritz Walter","El Capitán del Milagro","Capitán de Alemania Occidental, campeona sorpresa del Mundial 1954 conocido como 'el Milagro de Berna'."],
    ["Helmut Rahn","El Bombardero del Milagro","Delantero alemán autor del gol decisivo en la final del Mundial 1954."],
    ["Uwe Seeler","El Ídolo de Hamburgo","Delantero alemán que jugó cuatro Copas del Mundo, símbolo eterno del Hamburgo SV."],
    ["Paul Breitner","El Rebelde Alemán","Defensor alemán, uno de los pocos futbolistas en marcar en dos finales de Copas del Mundo distintas."],
    ["Karl-Heinz Rummenigge","Kalle","Delantero alemán bicampeón consecutivo del Balón de Oro a comienzos de los 80."],
    ["Lothar Matthäus","El Capitán de Hierro","Capitán de Alemania campeona del Mundial 1990, jugó cinco Copas del Mundo distintas."],
    ["Andreas Brehme","El Zurdo del Penal","Defensor alemán que convirtió el penal que le dio el título del Mundial 1990 a su país."],
    ["Rudi Völler","El del Bigote","Delantero alemán campeón del Mundial 1990, reconocible por su característico bigote."],
    ["Jürgen Klinsmann","El Aviador","Delantero alemán famoso por su festejo de gol simulando un clavado."],
    ["Oliver Kahn","El Pulpo Alemán","Arquero alemán, el único en la historia en ganar el premio al mejor jugador de un Mundial."],
    ["Günter Netzer","El Rebelde del 74","Volante alemán de estilo elegante, campeón del Mundial 1974 con Alemania Occidental."],
    ["Bernd Schuster","El Rubio de Alemania","Volante alemán de gran talento, brilló en el Barcelona y el Real Madrid en los 80."],
    ["Rubén Sosa","El Naza","Delantero uruguayo goleador que brilló en el fútbol italiano en los años 90."],
    ["Michel Salgado","El Lateral de Hierro","Defensor español, pieza fija del Real Madrid de los 'Galácticos' a comienzos de los 2000."],
    ["Julio Salinas","El Cañonero Vasco","Delantero español, parte del histórico 'Dream Team' del Barça de comienzos de los 90."],
    ["Manuel Sanchís","El Capitán de la Quinta","Defensor español, capitán histórico del Real Madrid formado en la cantera."],
    ["Iker Muniain","El Chico de Bilbao","Volante español, ídolo histórico del Athletic Club formado íntegramente en su cantera."],
    ["Marcos Senna","El Brasileño de España","Volante brasileño nacionalizado español, campeón de la Eurocopa 2008 con la Roja."],
    ["Kazimierz Deyna","El Elegante Polaco","Volante polaco, capitán de la sorprendente Polonia que salió tercera en el Mundial 1974."],
    ["Antonín Panenka","El Inventor del Panenka","Volante checoslovaco que inventó la famosa definición de penal suave por el medio del arco."],
    ["Ivo Viktor","El Arquero Checoslovaco","Arquero campeón de la Eurocopa 1976, la del histórico penal de Panenka."],
    ["František Plánička","El Pionero Checoslovaco","Arquero checoslovaco de los años 30, subcampeón del Mundial 1934."],
    ["Silvio Piola","El Rey Eterno de Italia","Delantero italiano, máximo goleador histórico de la Serie A durante más de 60 años."],
    ["Giuseppe Meazza","El Ídolo de Milán","Delantero italiano bicampeón del mundo en los años 30, el estadio de Inter y Milan lleva su nombre."],
    ["Gaetano Scirea","El Libero Elegante","Defensor italiano de estilo refinado, campeón del Mundial 1982 con la Juventus como base."],
    ["Dino Zoff","El Capitán más Viejo","Arquero italiano, el capitán de mayor edad en levantar una Copa del Mundo, en 1982."],
    ["Marco Tardelli","El del Grito Eterno","Volante italiano recordado por su festejo desgarrador tras el gol en la final del Mundial 1982."],
    ["Bruno Conti","El Habilidoso de la Azzurra","Extremo italiano, pieza clave en el ataque campeón del Mundial 1982."],
    ["Claudio Gentile","El Marcador Feroz","Defensor italiano famoso por su marca durísima sobre Maradona y Zico en el Mundial 1982."],
    ["José Manuel Moreno","El Charro","Delantero argentino de los años 40, parte de 'La Máquina' de River Plate, uno de los mejores equipos de la historia sudamericana."],
    ["Adolfo Pedernera","El Maestro","Delantero argentino, ídolo de 'La Máquina' de River Plate en los años 40."],
    ["Ángel Labruna","El Feo","Delantero argentino, máximo goleador histórico de River Plate durante décadas."],
    ["Valentino Mazzola","El Capitán del Grande Torino","Capitán del legendario Torino de finales de los años 40, uno de los mejores equipos de la historia italiana."],
    ["Roque Gastón Máspoli","El Arquero del Maracanazo","Arquero uruguayo campeón del histórico Mundial 1950 ante Brasil en el Maracaná."]
  ]

};
